spring:
  profiles:
    active: dev
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:elms_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:your_cryptographically_secure_random_key_minimum_32_chars}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 jam

elms:
  timezone: Asia/Jakarta
  attendance:
    work-start: "09:00"
  leave:
    default-balance: 12

server:
  port: 8080
