spring:
  profiles:
    active: dev
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:elms_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:default_jwt_secret_key_for_elms_development_environment_only_12345}
  expiration-ms: 86400000 # 24 jam

server:
  port: 8080